#!/bin/bash
#
# One liner that captures a QR code, and copy to clipboard
# From https://www.reddit.com/r/linux/comments/hw0crd/oneliner_to_read_onscreen_qr_codes/

sleep 0.2
import -silent  bmp:- | zbarimg -  2>/dev/null| grep 'QR-Code' | sed 's/QR-Code://'|xclip -selection clipboard
